import build_utils

Import(['env'])

akw_files = [
    'Module.py',
    'UUID.py',
    ]

sources = [
    'Initialize.cpp',
    ]

headers = [
    'Initialize.hpp',
    'Types.hpp',
    'Variant.hpp',
    ]

build_utils.build_shared_library(env,
                                 name='uuid',
                                 sources=sources,
                                 headers=headers,
                                 akw_files=akw_files)
