import build

Import(['env'])

akw_files = [
    'Queue.py',
    ]

sources = [
    'Initialize.cpp',
    ]

headers = [
    'Initialize.hpp',
    ]

build.shared_library(env,
                     # TODO: "Queue" in py2
                     name='queue',
                     sources=sources,
                     headers=headers,
                     akw_files=akw_files,
                     deps=[])
