import build_utils

Import(['env'])

akw_files = [
    'Date.py',
    'DateTime.py',
    'Time.py'
    ]

[env.AkwHeader(akw) for akw in akw_files]
akw_impls = [env.AkwImpl(akw) for akw in akw_files]

sources = [
    'Initialize.cpp',
    'Module.cpp',
    'TimeDelta.cpp',
    'TZInfo.cpp',
    ] + akw_impls

build_utils.build_shared_library(env,
                                 'ackward_datetime',
                                 sources,
                                 deps=['ackward_time'])
