import build_utils

Import(['env'])

akw_files = [
    'Date.akw',
    'DateTime.akw'
    ]

for akw in akw_files:
    env.AkwHeader(akw)
    env.AkwImpl(akw)

sources = [
    'Date.cpp',
    'DateTime.cpp',
    'Initialize.cpp',
    'Module.cpp',
    'TimeDelta.cpp',
    'TZInfo.cpp',
    ]

build_utils.build_shared_library(env,
                                 'datetime',
                                 sources,
                                 deps=['time'])
