import build

Import(['env'])

subdirs = [
    'embed',
    'extension',
    ]

SConscript(dirs=subdirs,
           exports='env')

programs = {
    'file_config_example': ['FileConfig.cpp'],
    'file_handler_example': ['FileHandler.cpp'],
    'filter_example': ['Filter.cpp'],
    'formatter_example': ['Formatter.cpp'],
    'handler_example': ['Handler.cpp'],
    'logger_example' : ['Logger.cpp'],
    'log_record_example': ['LogRecord.cpp'],
    }

for name, sources in programs.items():
    build.program(
        env,
        name,
        sources,
        deps=['core',
              'logging'])
