import build

Import(['env'])

subdirs = [
    'embed',
    'extension',
    ]

SConscript(dirs=subdirs,
           exports='env')

programs = {
    'file_config_example' : ['FileConfig.cpp'],
    }

for name, sources in programs.items():
    build.program(
        env,
        name,
        sources,
        deps=['core',
              'logging'])
