import build_utils

Import(['env'])

akw_files = [
    'Config.py',
    'Filter.py',
    'Module.py',
    ]

[env.AkwHeader(akw) for akw in akw_files]
akw_impls = [env.AkwImpl(akw) for akw in akw_files]

sources = [
    'Formatter.cpp',
    'Handler.cpp',
    'Initialize.cpp',
    'Logger.cpp',
    'LoggerAdapter.cpp',
    'LogRecord.cpp',
    'Types.cpp',
    ] + akw_impls

build_utils.build_shared_library(env,
                                 'ackward_logging',
                                 sources)
