import build_utils

Import(['env'])

akw_files = [
    'Config.py',
    'Filter.py',
    'Formatter.py',
    'Handler.py',
    'LoggerBase.py',
    'LogRecord.py',
    'Module.py',
    ]

[env.AkwHeader(akw) for akw in akw_files]
akw_impls = [env.AkwImpl(akw) for akw in akw_files]

sources = [
    'FileHandler.cpp',
    'Initialize.cpp',
    'Logger.cpp',
    #'LoggerAdapter.cpp',
    #'LogRecord.cpp',
    'NullHandler.cpp',
    'SocketHandler.cpp',
    'StreamHandler.cpp',
    'Types.cpp',
    'WatchedFileHandler.cpp',
    ] + akw_impls

build_utils.build_shared_library(env,
                                 'ackward_logging',
                                 sources)
