import build_utils

Import(['env'])

akw_files = [
    'Module.akw',
    ]

for akw in akw_files:
    env.AkwHeader(akw)
    env.AkwImpl(akw)

sources = [
    'Config.cpp',
    'Filter.cpp',
    'Formatter.cpp',
    'Handler.cpp',
    'Initialize.cpp',
    'Logger.cpp',
    'LoggerAdapter.cpp',
    'LogRecord.cpp',
    'Module.cpp',
    'Types.cpp',
    ]

build_utils.build_shared_library(env,
                                 'ackward_logging',
                                 sources)
