#ifndef ACKWARD_CODE_PYTHON_VERSION_HPP
#define ACKWARD_CODE_PYTHON_VERSION_HPP

#include <Python.h>

#define ACKWARD_PYTHON_MAJOR_VERSION PY_MAJOR_VERSION
#define ACKWARD_PYTHON_MINOR_VERSION PY_MINOR_VERSION
#define ACKWARD_PYTHON_VERSION PY_VERSION

#endif
