import build

Import('env')

sources = [
    'ByteArray.cpp',
    'Bytes.cpp',
    'ExceptionTranslation.cpp',
    'ExceptionTranslator.cpp',
    'GetClass.cpp',
    'Import.cpp',
    'Initialize.cpp',
    'Kwargs.cpp',
    'Object.cpp',
    'Util.cpp',
    'Version.cpp',
]

headers = [
    'ByteArray.hpp',
    'Bytes.hpp',
    'Enum.hpp',
    'Exceptions.hpp',
    'ExceptionTranslation.hpp',
    'ExceptionTranslator.hpp',
    'GetClass.hpp',
    'Import.hpp',
    'Initialize.hpp',
    'Iterable.hpp',
    'Kwargs.hpp',
    'Object.hpp',
    'PythonConverter.hpp',
    'Tuple.hpp',
    'Util.hpp',
    'Version.hpp',
    ]

build.shared_library(
    env,
    'core',
    sources,
    headers)
