import bygg

Import('env')

sources = [
    'ByteArray.cpp',
    'Bytes.cpp',
    'Exceptions.cpp',
    'ExceptionTranslator.cpp',
    'GetClass.cpp',
    'Import.cpp',
    'Initialize.cpp',
    'Object.cpp',
    'Util.cpp'
]

headers = [
    'ByteArray.hpp',
    'Bytes.hpp',
    'Enum.hpp',
    'Exceptions.hpp',
    'ExceptionTranslator.hpp',
    'GetClass.hpp',
    'Import.hpp',
    'Initialize.hpp',
    'Iterable.hpp',
    'Object.hpp',
    'PythonConverter.hpp',
    'Tuple.hpp',
    'Util.hpp',
    ]

bygg.build_shared_library(env,
                          'core',
                          sources,
                          headers)
