import build

Import(['env'])

programs = {
    'bytearray_example' : ['ByteArray.cpp'],
    'bytes_example' : ['Bytes.cpp'],
    'exception_translation_example' : ['ExceptionTranslation.cpp'],
    'exception_translator_example' : ['ExceptionTranslator.cpp'],
    'exceptions_example' : ['Exceptions.cpp'],
    'find_object_example' : ['FindObject.cpp'],
    'get_class_example' : ['GetClass.cpp'],
    'import_example' : ['Import.cpp'],
    }

for name, sources in programs.items():
    build.program(
        env,
        name,
        sources,
        deps=['core'])
