import build

Import(['env'])

programs = {
    'bytearray_example' : ['ByteArray.cpp'],
    'bytes_example' : ['Bytes.cpp'],
    }

for name, sources in programs.items():
    build.program(
        env,
        name,
        sources,
        deps=['core'])
