import build

Import(['env'])

programs = {
    'bytearray_example' : ['ByteArray.cpp'],
    'bytes_example' : ['Bytes.cpp'],
    'exception_translation_example' : ['ExceptionTranslation.cpp'],
    'exception_translator_example' : ['ExceptionTranslator.cpp'],
    'exceptions_example' : ['Exceptions.cpp'],
    'find_object_example' : ['FindObject.cpp'],
    'get_class_example' : ['GetClass.cpp'],
    'import_example' : ['Import.cpp'],
    'initialize_example' : ['Initialize.cpp'],
    'object_example' : ['Object.cpp'],
    'property_example' : ['Property.cpp'],
    'python_converter_example' : ['PythonConverter.cpp'],
    'python_version_example' : ['PythonVersion.cpp'],
    'tuple_explicit_example' : ['TupleExplicit.cpp'],
    }

for name, sources in programs.items():
    build.program(
        env,
        name,
        sources,
        deps=['core'])
