import build

Import(['env'])

akw_files = [
    'Module.py'
    ]

sources = [
    'Initialize.cpp',
    ]

headers = [ 
    'Initialize.hpp',
    ]

build.shared_library(
    env,
    name='time',
    sources=sources,
    headers=headers,
    akw_files=akw_files)
