import build_utils

Import(['env'])

akw_files = [
    'Module.py'
    ]

sources = [
    'Initialize.cpp',
    ]

headers = [ 
    'Initialize.hpp',
    'Module_akw.hpp',
    ]

build_utils.build_shared_library(env,
                                 name='time',
                                 sources=sources,
                                 headers=headers,
                                 akw_files=akw_files)
