import build_utils

Import(['env'])

akw_files = [
    'Module.py'
    ]

sources = [
    # 'Initialize.cpp',
    ]

headers = [ 
    # 'Initialize.hpp',
    ]

build_utils.build_shared_library(env,
                                 name='re',
                                 sources=sources,
                                 headers=headers,
                                 akw_files=akw_files)
