import build

Import(['env'])

akw_files = [
    'MatchObject.py',
    'Module.py',
    'RegexObject.py',
    ]

sources = [
    # 'Initialize.cpp',
    ]

headers = [ 
    # 'Initialize.hpp',
    ]

build.shared_library(env,
                     name='re',
                     sources=sources,
                     headers=headers,
                     akw_files=akw_files)
